name: scancontrol
services:
  scancontrol-service:
    extends:
      file: docker-compose.yml
      service: scancontrol-service
    build:
      context: ${SCANCONTROL_SRC_DIR}
      dockerfile: .docker/dev.Dockerfile
      args:
        - TARGET_WS=${SCANCONTROL_TARGET_WS}
    image: "scancontrol:latest"